version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dreamjob
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    restart: always
  job4j_dreamjob:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/dreamjob
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=1234
      - JDBC_DRIVER=org.postgresql.Driver
    container_name: job4j_dreamjob
    depends_on:
      - db